export const TOGGLE_ERROR = "TOGGLE_ERROR"
export const LOADING = "LOADING"
export const SET_QUESTION = "SET_QUESTION"
export const SET_ANSWER = "SET_ANSWER"
export const SET_PARAGRAPH = "SET_PARAGRAPH"